version: "3.9"

x-nginx-image: &nginx-image nginx:alpine
x-geoserver-image: &geoserver-image kartoza/geoserver:2.18.2

#
# SERVICES
#

services:

  ############################################################
  #
  # First we define all default services that are run if
  # you do not specify a profile. These are currently
  # nginx, hugo watcher, filebrowser, postgres and others
  #
  ############################################################


  # Nginx with ssl      
  nginx:
    image: *nginx-image
    volumes:
      - ./conf/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx_conf/servername.conf:/etc/nginx/servername.conf
      - ./conf/nginx_conf/locations:/etc/nginx/locations

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # For debugging config issues
    #command: "sleep 3000"
    ports:
      - "80:80"
    networks:
      - os-gis-stack
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: '10'

  geoserver:
    image: *geoserver-image
    container_name: "geoserver"
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}

        ' --output /dev/null http://127.0.0.1:8080/geoserver"
      interval: 60s
      timeout: 10s
      retries: 1
      start_period: 60s
    user: 1000:1000
    depends_on:
      - nginx    
    # env_file:
    #   # Editable configs (will be edited by make configure or by user)
    #   - .env
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=geoserver
      # - ADMIN_USERNAME=${GEOSERVER_ADMIN_USER}
      # - ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      # - INITIAL_MEMORY=${INITIAL_MEMORY}
      # - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - STABLE_EXTENSIONS=importer-plugin
      # - HTTPS_HOST=${DOMAIN}
      # - HTTPS_PORT=443
      - HTTP_HOST=127.0.0.1
      - HTTP_PORT=80
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
    # volumes:
    #   # This path is specified by the GEOSERVER_DATA_DIR
    #   - geoserver_data:/opt/geoserver/data_dir
    #   # Mounted in to geoserver for serving geoserver data
    #   # store
    #   - geoserver_user_data:/geoserver_user_data
    restart: on-failure
    networks:
      - os-gis-stack   
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: '10'

networks:
  os-gis-stack:
